version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "security" 